version: 0.0
Resources:
- TargetService:
Type: AWS::ECS::Service
Properties:
TaskDefinition: "arn:aws:ecs:us-east-1:156962844638:task-definition/saritha-pms-auth-task-definition:1"
LoadBalancerInfo:
ContainerName: "saritha-pms-auth-container"
ContainerPort: 8104
PlatformVersion: "LATEST"
